name: steel_crypt_pc335
description: A comprehensive library of high-level, cryptographic APIs. This library supports hashing, password hashing,
  two-way encryption, MAC authentication, and key/IV generation.
version: 3.0.0+1
homepage: https://github.com/AKushWarrior/steel_crypt
repository: https://github.com/AKushWarrior/steel_crypt
issue_tracker: https://github.com/AKushWarrior/steel_crypt_pc335/issues

executables:
  decrypt: decrypt
  encrypt: encrypt
  genkey: genkey
  hashtext: hashtext

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  pointycastle_pc335:
    git:
      url: https://github.com/hakali/pc-dart.git
      ref: pc-335

dev_dependencies:
  pedantic: ^1.11.0

